spring:
  application:
    name: erp-platform
  profiles:
    active: ${PROFILE:dev}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:dev}
      config:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        file-extension: yaml
        namespace: ${NACOS_NAMESPACE:dev}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/cnc_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:erp}
    password: ${MYSQL_PASSWORD:erp123}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:9081}

app:
  v137:
    prd_version: V1.3.7
    contract_id: XP-ZPF202606082405
  crypto:
    dek-file: ${DEK_FILE:/etc/erp/dek.key}
  security:
    jwt:
      secret: ${JWT_SECRET:dev-only-secret-please-replace-in-prod-2026}
      access-ttl-seconds: 7200
      refresh-ttl-seconds: 604800
  minio:
    endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
    access-key: ${MINIO_ACCESS_KEY:minio}
    secret-key: ${MINIO_SECRET_KEY:minio123}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted

logging:
  level:
    root: INFO
    com.btsheng.erp: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"
